version: '2'

services:
  microtransactionsapi:
    container_name: microtransactionsapi
    image: petprojects/micro-transactions-api:${BUILD_VERSION}
    network_mode: bridge
    environment:
      - 'MTS_APP_SETTINGS_ConsulStoreConfiguration:Environment=${CONSUL_ENVIRONMENT}'
      - 'MTS_APP_SETTINGS_ConsulClientConfiguration:Address=${CONSUL_ADDRESS}'
    build:
      context: ./src/Presentation.Api
      dockerfile: Dockerfile
      args:
        source: ${OUTPUT_PATH}
