version: '2'

services:
  microtransactionsapi:
    container_name: microtransactionsapi
    image: petprojects/micro-transactions-api:${BUILD_VERSION}
    network_mode: bridge
    build:
      context: ./src/Presentation.Api
      dockerfile: Dockerfile
      args:
        source: ${OUTPUT_PATH}
